[project]
name = 'Content-Monetization-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.content-nft]
path = 'contracts/content-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.subscription]
path = 'contracts/subscription.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
